import unittest
from pathlib import Path


class HomepageCleanupTests(unittest.TestCase):
    def test_hero_logo_markup_and_styles_are_still_present(self):
        template_text = Path("render/dashboard_template.html").read_text(encoding="utf-8")
        css_text = Path("render/style.css").read_text(encoding="utf-8")

        self.assertIn('class="hero-logo-col"', template_text)
        self.assertIn('src="asset/amw.webp"', template_text)
        self.assertIn('.hero-logo-col .main-logo', css_text)

    def test_homepage_campaign_chronicle_surface_was_removed(self):
        template_text = Path("render/dashboard_template.html").read_text(encoding="utf-8")
        script_text = Path("render/script.js").read_text(encoding="utf-8")
        cards_text = Path("render/src/js/features/home_analytics/analytics_cards.js").read_text(encoding="utf-8")
        css_text = Path("render/style.css").read_text(encoding="utf-8")
        search_css_text = Path("render/src/css/features/search/autocomplete.css").read_text(encoding="utf-8")
        html_dashboard_text = Path("render/html_dashboard.py").read_text(encoding="utf-8")

        self.assertIn('class="home-roster-intelligence-section"', template_text)
        self.assertIn('id="home-roster-intelligence-sync"', template_text)
        self.assertIn('Roster Intelligence', template_text)
        self.assertIn('How these numbers are counted', template_text)
        self.assertIn('Metric Scope', template_text)
        self.assertIn('Guild Roster:</strong> raw guild roster total from the roster endpoint, including mains and alts.', template_text)
        self.assertIn('Roster Movement:</strong> guild membership snapshots used to detect joins, departures, and rejoins, so its baseline can differ from raw roster totals and detail-eligible processed counts.', template_text)
        self.assertIn('Level Distribution <span class="chart-title-sub">Roster-known Levels</span>', template_text)
        self.assertIn('Movement, recent changes, and officer health from the latest guild snapshot.', template_text)
        self.assertIn('Dashboard built: {{ last_updated_display }}', template_text)
        self.assertIn('class="home-insights-row"', template_text)
        self.assertIn('id="home-latest-changes-card"', template_text)
        self.assertIn('id="home-officer-brief-card"', template_text)
        self.assertIn('Recent activity, trend shifts, and roster count changes worth noting.', template_text)
        self.assertIn('class="dashboard-footer"', template_text)
        self.assertIn('Dashboard Built', template_text)
        self.assertIn('Contact: <a href="mailto:nullbit5@protonmail.com">nullbit5@protonmail.com</a>', template_text)
        self.assertIn('href="#campaign-archive"', template_text)
        self.assertIn('View Campaign Archive', template_text)
        self.assertIn('Campaign Archive', template_text)
        self.assertNotIn('https://github.com/parvagans/Azeroths-Most-Wanted', template_text)
        self.assertNotIn('class="nav-btn nav-btn-source"', template_text)
        self.assertNotIn('class="footer-source-info"', template_text)
        self.assertIn('id="backToTopBtn"', template_text)
        self.assertIn('last_updated_display=last_updated_display', html_dashboard_text)
        self.assertIn('os.path.join(base_dir, "src", "css", "features", "search", "autocomplete.css")', html_dashboard_text)
        self.assertIn('.home-insights-row {', css_text)
        self.assertIn('.home-roster-intelligence-section {', css_text)
        self.assertIn('.home-roster-intelligence-sync {', css_text)
        self.assertIn('.home-metric-scope {', css_text)
        self.assertIn('.home-metric-scope-summary {', css_text)
        self.assertIn('.home-metric-scope-summary:focus-visible {', css_text)
        self.assertIn('.home-metric-scope-panel {', css_text)
        self.assertNotIn('.search-box:has(input:focus-visible) {', css_text)
        self.assertNotIn('.hero-search-box:has(input:focus-visible) {', css_text)
        self.assertIn('.search-box:has(input:focus-visible) {', search_css_text)
        self.assertIn('.hero-search-box:has(input:focus-visible) {', search_css_text)
        self.assertIn('.hero-search-wrapper {', search_css_text)
        self.assertIn('.hero-ac-item {', search_css_text)
        self.assertIn('@media (max-width: 1024px) {', search_css_text)
        self.assertIn('.concise-view-header {', css_text)
        self.assertIn('.concise-view-context {', css_text)
        self.assertIn('.concise-back-btn {', css_text)
        self.assertIn('.concise-back-btn:focus-visible {', css_text)
        self.assertIn('.dashboard-footer {', css_text)
        self.assertIn('.footer-disclaimer {', css_text)
        self.assertNotIn('analytics-intel-section-chronicle', template_text)
        self.assertNotIn('Campaign Chronicle', template_text)
        self.assertNotIn('Recent Campaign Activity', template_text)
        self.assertNotIn('Campaign Chronicle', script_text)
        self.assertNotIn('Recent Campaign Activity', script_text)
        self.assertNotIn('analytics-chronicle', css_text)
        self.assertNotIn('search-autocomplete', css_text)
        self.assertNotIn('applyChronicleCard', cards_text)

    def test_navigation_context_and_return_controls_are_present(self):
        template_text = Path("render/dashboard_template.html").read_text(encoding="utf-8")
        script_text = Path("render/script.js").read_text(encoding="utf-8")
        shell_text = Path("render/src/js/features/command_hall/command_shell.js").read_text(encoding="utf-8")

        self.assertIn('id="concise-view-context"', template_text)
        self.assertIn('id="concise-back-btn"', template_text)
        self.assertIn('Back to overview', template_text)
        self.assertIn('No matching character found. Try a character name or a shorter search.', template_text)
        self.assertIn('Viewing: full roster. Filter: all scanned mains and alts.', shell_text)
        self.assertIn('Viewing: active roster. Filter: mains seen in the last 14 days.', shell_text)
        self.assertIn('Viewing: raid-ready roster. Filter: mains meeting the configured readiness threshold.', shell_text)
        self.assertIn('Character dossier •', script_text)

    def test_search_autocomplete_helpers_are_present(self):
        script_text = Path("render/script.js").read_text(encoding="utf-8")

        self.assertIn('const CHARACTER_SEARCH_MIN_QUERY_LENGTH = 2;', script_text)
        self.assertIn('function normalizeCharacterSearchQuery(query)', script_text)
        self.assertIn('function getCharacterSearchRank(char, normalizedQuery)', script_text)
        self.assertIn('function clearCharacterSearchPanels({ clearInputs = false } = {})', script_text)
        self.assertIn('function renderCharacterSearchAutocomplete(targetEl, query, { limit = 6, forceObjectFitCover = false } = {})', script_text)
        self.assertIn('renderCharacterSearchAutocomplete(heroSearchAutoComplete, e.target.value, { limit: 6 });', script_text)
        self.assertIn('renderCharacterSearchAutocomplete(searchAutoComplete, e.target.value, { limit: 6, forceObjectFitCover: true });', script_text)
        self.assertIn('clearCharacterSearchPanels({ clearInputs: true });', script_text)
        self.assertIn('if (name === normalizedQuery) return 0;', script_text)
        self.assertIn('if (name.startsWith(normalizedQuery)) return 1;', script_text)
        self.assertIn('if (name.includes(normalizedQuery)) return 2;', script_text)

    def test_character_dossier_timeline_support_remains_intact(self):
        script_text = Path("render/script.js").read_text(encoding="utf-8")

        self.assertIn('timeline-character-dossier', script_text)
        self.assertIn("title: `📜 ${formattedName}'s Recent Activity`", script_text)
        self.assertIn("subtitle: 'Recent loot drops, level gains, and earned honors recorded for this hero.'", script_text)


if __name__ == "__main__":
    unittest.main()
