import json
import unittest
from pathlib import Path


class CharacterIntelligenceRenderTests(unittest.TestCase):
    def test_dossier_template_includes_character_intelligence_hook(self):
        template_text = Path("render/dashboard_template.html").read_text(encoding="utf-8")

        self.assertIn('class="info-box char-card-intelligence-shell"', template_text)
        self.assertIn('class="char-card-intelligence-profile"', template_text)

    def test_character_tooltip_badges_wrap_without_capping_rendered_badges(self):
        template_text = Path("render/dashboard_template.html").read_text(encoding="utf-8")
        runtime_text = Path("render/script.js").read_text(encoding="utf-8")
        style_css_text = Path("render/style.css").read_text(encoding="utf-8")
        dossier_css_text = Path("render/src/css/features/character/dossier.css").read_text(encoding="utf-8")
        mobile_css_text = Path("render/src/css/features/mobile/mobile.css").read_text(encoding="utf-8")

        self.assertIn('class="tooltip-badges-container"', template_text)
        self.assertIn("badgesContainer.className = 'tt-badge-container';", runtime_text)
        self.assertIn("badgesContainer.appendChild(badge);", runtime_text)

        tooltip_badge_start = runtime_text.index("const addBadge = (count, title, cssClass, icon, label = null) => {")
        tooltip_badge_end = runtime_text.index("addBadge(pveGold, tPveGold", tooltip_badge_start)
        tooltip_badge_render_text = runtime_text[tooltip_badge_start:tooltip_badge_end]
        self.assertNotIn(".slice(", tooltip_badge_render_text)
        self.assertNotIn("removeChild", tooltip_badge_render_text)
        self.assertNotIn("badge.remove()", tooltip_badge_render_text)

        badge_container_start = dossier_css_text.index(".tt-badge-container {")
        badge_container_end = dossier_css_text.index("}", badge_container_start)
        badge_container_rule = dossier_css_text[badge_container_start:badge_container_end]
        self.assertIn("display: inline-flex;", badge_container_rule)
        self.assertIn("flex-wrap: wrap;", badge_container_rule)
        self.assertIn("max-width: 100%;", badge_container_rule)
        self.assertIn("min-width: 0;", badge_container_rule)
        self.assertIn("overflow: hidden;", badge_container_rule)

        badge_chip_start = dossier_css_text.index(".tt-badge {")
        badge_chip_end = dossier_css_text.index("}", badge_chip_start)
        badge_chip_rule = dossier_css_text[badge_chip_start:badge_chip_end]
        self.assertIn("flex: 0 0 auto;", badge_chip_rule)
        self.assertIn("max-width: 100%;", badge_chip_rule)
        self.assertIn("box-sizing: border-box;", badge_chip_rule)

        tooltip_shell_start = style_css_text.rfind(
            ".custom-tooltip {",
            0,
            style_css_text.index("width: min(348px, calc(100vw - 24px));"),
        )
        tooltip_shell_end = style_css_text.index("}", tooltip_shell_start)
        tooltip_shell_rule = style_css_text[tooltip_shell_start:tooltip_shell_end]
        self.assertIn("width: min(348px, calc(100vw - 24px));", tooltip_shell_rule)
        self.assertIn("max-width: calc(100vw - 24px);", tooltip_shell_rule)
        self.assertIn("box-sizing: border-box;", tooltip_shell_rule)
        self.assertIn("overflow: hidden;", tooltip_shell_rule)

        tooltip_name_start = style_css_text.index(".custom-tooltip .tt-name {")
        tooltip_name_end = style_css_text.index("}", tooltip_name_start)
        tooltip_name_rule = style_css_text[tooltip_name_start:tooltip_name_end]
        self.assertIn("display: flex;", tooltip_name_rule)
        self.assertIn("flex-wrap: wrap;", tooltip_name_rule)
        self.assertIn("max-width: 100%;", tooltip_name_rule)
        self.assertIn("min-width: 0;", tooltip_name_rule)
        self.assertIn(".custom-tooltip .tooltip-char-name {", style_css_text)

        self.assertIn(".custom-tooltip .tt-badge-container {", mobile_css_text)
        self.assertIn("flex-wrap: wrap;", mobile_css_text)
        self.assertIn("max-width: calc(100vw - 16px);", mobile_css_text)

    def test_dossier_js_includes_prestige_identity_and_reigning_header(self):
        html_dashboard_text = Path("render/html_dashboard.py").read_text(encoding="utf-8")
        core_data_text = Path("render/src/js/core/data.js").read_text(encoding="utf-8")
        js_text = Path("render/src/js/features/character_dossier/dossier_view.js").read_text(encoding="utf-8")
        runtime_text = Path("render/script.js").read_text(encoding="utf-8")
        style_css_text = Path("render/style.css").read_text(encoding="utf-8")
        css_text = Path("render/src/css/features/character/dossier.css").read_text(encoding="utf-8")

        self.assertIn('os.path.join(base_dir, "src", "css", "features", "character", "dossier.css")', html_dashboard_text)
        self.assertIn("function buildDossierIntelligencePanel", js_text)
        self.assertIn("function buildDossierOfficerBriefPanel", js_text)
        self.assertIn("function buildDossierIntelligenceSection", js_text)
        self.assertIn("function getDossierIdentitySnapshot", js_text)
        self.assertIn("function getDossierMovementSnapshot", js_text)
        self.assertIn("function buildDossierOfficerNotes", js_text)
        self.assertIn("function buildDossierRecognitionItems", js_text)
        self.assertIn("function formatDossierRecognitionDate", js_text)
        self.assertNotIn("function getDossierRecognitionHistoryLines", js_text)
        self.assertNotIn("function getDossierReigningWeekLabel", js_text)
        self.assertIn("function formatDossierBadgeHistoryEntry", js_text)
        self.assertIn("function buildDossierBadgeHistory", js_text)
        self.assertIn("function buildDossierReigning", js_text)
        self.assertIn("function buildDossierPrestigeShowcase", js_text)
        self.assertIn("Officer Brief", js_text)
        self.assertIn("Recognition Record", js_text)
        self.assertIn("Awards & Footprint", js_text)
        self.assertIn("Prestige Showcase", js_text)
        self.assertIn("Reigning iLvl Champion", js_text)
        self.assertIn("Reigning HK Champion", js_text)
        self.assertIn("Biggest Upgrades / iLvl", js_text)
        self.assertIn("Deadliest / HKs", js_text)
        self.assertIn("const prevMvps = dashboardConfig && typeof dashboardConfig === 'object'", js_text)
        self.assertIn("const hasCurrentPrevMvp = Boolean((prevMvps.pve && prevMvps.pve.name) || (prevMvps.pvp && prevMvps.pvp.name));", js_text)
        self.assertIn("function normalizeHallOfHeroesBadgeType(rawType = '')", core_data_text)
        self.assertIn("if (cleanType === \"warden's standard\") return 'readiness';", core_data_text)
        self.assertIn("if (cleanType === \"warden's standard vanguard\") return 'readiness';", core_data_text)
        self.assertIn("replace(/\\u2019/g, \"'\")", core_data_text)
        self.assertIn("tt-badge-weekly-loot", js_text)
        self.assertIn("tt-badge-weekly-xp", js_text)
        self.assertIn("tt-badge-weekly-hks", js_text)
        self.assertIn("tt-badge-weekly-zenith", js_text)
        self.assertIn("tt-badge-weekly-readiness", js_text)
        self.assertIn("tt-badge-vanguard", js_text)
        self.assertIn("tt-badge-gold", js_text)
        self.assertIn("tt-badge-silver", js_text)
        self.assertIn("tt-badge-bronze", js_text)
        self.assertIn("tt-badge-pve c-badge-reigning c-badge-reigning-pve", js_text)
        self.assertIn("tt-badge-pvp c-badge-reigning c-badge-reigning-pvp", js_text)
        self.assertIn("const DOSSIER_PRESTIGE_ICONS = Object.freeze({", js_text)
        self.assertIn("dragonHoard: '\\u{1F409}'", js_text)
        self.assertIn("heroJourney: '\\u{1F6E1}\\uFE0F'", js_text)
        self.assertIn("bloodEnemy: '\\u{1FA78}'", js_text)
        self.assertIn("zenith: '\\u26A1\\uFE0F'", js_text)
        self.assertIn("readiness: '\\u{1F3F0}'", js_text)
        self.assertIn("vanguard: '\\u{1F396}\\uFE0F'", js_text)
        self.assertIn("crown: '\\u{1F451}'", js_text)
        self.assertIn("sword: '\\u2694\\uFE0F'", js_text)
        self.assertIn("gold: '\\u{1F947}'", js_text)
        self.assertIn("silver: '\\u{1F948}'", js_text)
        self.assertIn("bronze: '\\u{1F949}'", js_text)
        self.assertIn("const reigningIconByCategory = {", js_text)
        self.assertIn("badgeText: label,", js_text)
        self.assertIn("pve: DOSSIER_PRESTIGE_ICONS.crown,", js_text)
        self.assertIn("pvp: DOSSIER_PRESTIGE_ICONS.sword", js_text)
        self.assertIn("const vanguardBadges = safeParseArray(profile?.vanguard_badges || source?.vanguard_badges);", js_text)
        self.assertIn("const campaignBadges = safeParseArray(profile?.campaign_badges || source?.campaign_badges);", js_text)
        self.assertIn("const readinessBadges = campaignBadges.filter(type => normalizeHallOfHeroesBadgeType(type) === 'readiness');", js_text)
        self.assertIn("count: campaignBadges.filter(type => normalizeHallOfHeroesBadgeType(type) === 'readiness').length,", js_text)
        self.assertIn("const readinessCount = campaignBadgeTypes.filter(type => type === 'readiness').length;", js_text)
        self.assertIn("const visibleFootprint = snapshot.footprint.filter(item => item && (item.value > 0 || item.tone === 'zenith' || item.tone === 'readiness'));", js_text)
        self.assertIn("badgeTypes: ['vanguard'],", js_text)
        self.assertIn("badgeTypes: ['readiness'],", js_text)
        self.assertIn("label: \"Warden's Standard\",", js_text)
        self.assertIn("readiness: 3,", js_text)
        self.assertIn("pve_gold: 6,", js_text)
        self.assertIn(".slice(0, 12);", js_text)
        self.assertIn("item.value > 0 || item.tone === 'zenith' || item.tone === 'readiness'", js_text)
        self.assertLess(js_text.index("readiness: 3,"), js_text.index("pve_gold: 6,"))
        self.assertLess(js_text.index("readiness: 3,"), js_text.index("pvp_gold: 9,"))
        self.assertNotIn("const reigningDetails = document.createElement('details');", js_text)
        self.assertNotIn("const reigningSummary = document.createElement('summary');", js_text)
        self.assertIn("const reigningCard = document.createElement('div');", js_text)
        self.assertIn("char-card-commendation-showcase-item-reigning-static", js_text)
        self.assertIn("char-card-commendation-showcase-summary-reigning-static", js_text)
        self.assertIn("const DASHBOARD_BADGE_ICONS = Object.freeze({", runtime_text)
        self.assertIn("crown: '\\u{1F451}'", runtime_text)
        self.assertIn("sword: '\\u2694\\uFE0F'", runtime_text)
        self.assertIn("gold: '\\u{1F947}'", runtime_text)
        self.assertIn("silver: '\\u{1F948}'", runtime_text)
        self.assertIn("bronze: '\\u{1F949}'", runtime_text)
        self.assertIn("vanguard: '\\u{1F396}\\uFE0F'", runtime_text)
        self.assertIn("shield: '\\u{1F6E1}\\uFE0F'", runtime_text)
        self.assertIn("blood: '\\u{1FA78}'", runtime_text)
        self.assertIn("dragon: '\\u{1F409}'", runtime_text)
        self.assertIn("lightning: '\\u26A1\\uFE0F'", runtime_text)
        self.assertIn("readiness: '\\u{1F3F0}'", runtime_text)
        self.assertIn("function getReadinessBadgeState(vanguardBadges = [], campaignBadgeTypes = [])", runtime_text)
        self.assertIn("badge-war-readiness", runtime_text)
        self.assertIn("c-badge-weekly-readiness", runtime_text)
        self.assertIn("appendFullCardBadge(headerBadgesEl, {", runtime_text)
        self.assertIn("const headerBadgesEl = clone.querySelector('.char-card-header-badges') || clone.querySelector('.char-badges-container');", runtime_text)
        self.assertIn("const headerReigningSlotEl = clone.querySelector('.char-card-header-reigning-slot') || headerBadgesEl;", runtime_text)
        self.assertIn("const equippedIlvl = parseInt(identity.equippedIlvl || 0, 10) || 0;", runtime_text)
        self.assertIn("if (equippedIlvl > 0) {", runtime_text)
        self.assertIn("text: `iLvl ${equippedIlvl.toLocaleString()}`,", runtime_text)
        self.assertIn("text: guildRank,", runtime_text)
        self.assertIn("text: readinessLabel,", runtime_text)
        self.assertLess(
            runtime_text.index("text: `iLvl ${equippedIlvl.toLocaleString()}`,"),
            runtime_text.index("text: guildRank,"),
        )
        self.assertLess(
            runtime_text.index("text: guildRank,"),
            runtime_text.index("text: readinessLabel,"),
        )
        header_block = runtime_text[runtime_text.index("const headerBadgesEl = clone.querySelector('.char-card-header-badges') || clone.querySelector('.char-badges-container');"):runtime_text.index("const reigningBadges = typeof buildDossierReigning === 'function'")]
        self.assertNotIn("text: `${DASHBOARD_BADGE_ICONS.readiness} ${readinessState.count}`", header_block)
        self.assertNotIn("classNames: ['badge-war-readiness']", header_block)
        self.assertNotIn("title: tReadiness,", header_block)
        self.assertIn("const vanguardRequested = cleanBadgeTypes.includes('vanguard');", js_text)
        self.assertIn("const warEffortEntries = Array.isArray(week?.war_effort) ? week.war_effort : [];", js_text)
        self.assertIn("const isVanguard = vanguards.some(name => String(name || '').trim().toLowerCase() === targetName);", js_text)
        self.assertIn("key: `archive_${weekAnchor}_vanguard_${type}`", js_text)
        self.assertIn("detail: `${dateLabel} ${DOSSIER_PRESTIGE_SEPARATOR} ${categoryLabel} ${DOSSIER_PRESTIGE_SEPARATOR} ${medalLabel} ${DOSSIER_PRESTIGE_SEPARATOR} Rank #${rank} ${DOSSIER_PRESTIGE_SEPARATOR} Score ${score.toLocaleString()}`", js_text)
        self.assertIn("detail: type === 'readiness'", js_text)
        self.assertIn("const readinessCopy = isVanguard", js_text)
        self.assertIn("detail: `${dateLabel} ${DOSSIER_PRESTIGE_SEPARATOR} ${sourceLabel} / ${categoryLabel} ${DOSSIER_PRESTIGE_SEPARATOR} Vanguard`", js_text)
        self.assertIn("detail: `${dateLabel} ${DOSSIER_PRESTIGE_SEPARATOR} ${displayName}`", js_text)
        self.assertIn("summaryCount.textContent = `x${item.count}`;", js_text)
        self.assertIn("summaryIcon.textContent = item.icon;", js_text)
        self.assertIn("if (readinessState.count > 0) awardsAttr.push('readiness');", runtime_text)
        self.assertIn("const readinessState = getReadinessBadgeState(vBadges, campaignBadgeTypes);", runtime_text)
        self.assertIn("const tReadiness = getDetailedBadgeTooltip(p.name, ['readiness'], readinessState.title, readinessState.count);", runtime_text)
        self.assertIn("addBadge(readinessState.count, tReadiness, 'tt-badge-weekly-readiness', DASHBOARD_BADGE_ICONS.readiness);", runtime_text)
        self.assertIn("text: `${DASHBOARD_BADGE_ICONS.readiness} ${readinessState.count}`,", runtime_text)
        self.assertIn("classNames: ['c-badge-pill', 'c-badge-weekly-readiness']", runtime_text)
        self.assertIn("getReadinessBadgeState(vBadges, campaignBadgeTypes)", runtime_text)
        self.assertIn("const headerReigningSlotEl = clone.querySelector('.char-card-header-reigning-slot') || headerBadgesEl;", runtime_text)
        self.assertIn("appendFullCardReigningBadge(headerReigningSlotEl, reigningInfo, index === 0);", runtime_text)
        self.assertIn("badge.style.cursor = 'default';", runtime_text)
        self.assertIn("const reigningBadges = typeof buildDossierReigning === 'function'", runtime_text)
        self.assertIn("buildDossierReigning({", runtime_text)
        self.assertIn("profile: p,", runtime_text)
        self.assertIn("source: char,", runtime_text)
        self.assertIn("const equippedIlvl = parseInt(identity.equippedIlvl || 0, 10) || 0;", runtime_text)
        self.assertIn("if (equippedIlvl > 0) {", runtime_text)
        self.assertIn("text: `iLvl ${equippedIlvl.toLocaleString()}`,", runtime_text)
        self.assertLess(
            runtime_text.index("const equippedIlvl = parseInt(identity.equippedIlvl || 0, 10) || 0;"),
            runtime_text.index("text: `iLvl ${equippedIlvl.toLocaleString()}`,"),
        )
        self.assertLess(
            runtime_text.index("text: `iLvl ${equippedIlvl.toLocaleString()}`,"),
            runtime_text.index("text: readinessLabel,"),
        )
        self.assertNotIn("addBadge(isPveReigning ? 1 : 0, 'Current Reigning PvE Champion!', 'tt-badge-pve', '\U0001F451', '\U0001F451 Reign');", runtime_text)
        self.assertNotIn("addBadge(isPvpReigning ? 1 : 0, 'Current Reigning PvP Champion!', 'tt-badge-pvp', '\u2694\ufe0f', '\u2694\ufe0f Reign');", runtime_text)
        self.assertIn("Dragon's Hoard", js_text)
        self.assertIn("Blood of the Enemy", js_text)
        self.assertIn("Warden's Standard", js_text)
        self.assertIn("Campaign / Readiness", js_text)
        self.assertNotIn("Warden's Standard mark", js_text)
        self.assertIn("Warden's Standard: maintained active raid-ready status this week.", js_text)
        self.assertIn("Warden's Standard Vanguard: top 3 active raid-ready profiles by equipped item level.", js_text)
        self.assertIn("Latest archive week:", js_text)
        self.assertNotIn("PvE Ladder Medals", js_text)
        self.assertNotIn("PvP Ladder Medals", js_text)
        self.assertNotIn("icon: 'DH'", js_text)
        self.assertNotIn("icon: 'HJ'", js_text)
        self.assertNotIn("icon: 'BoE'", js_text)
        self.assertNotIn("icon: 'ZN'", js_text)
        self.assertNotIn("icon: 'VG'", js_text)
        self.assertNotIn("icon: 'WS'", js_text)
        self.assertNotIn("icon: 'READY'", js_text)
        self.assertNotIn("icon: 'WARDEN'", js_text)
        self.assertNotIn("__amwReadinessPatched", js_text)
        self.assertNotIn("patchedGetHallOfHeroes", js_text)
        self.assertNotIn("patchedApplyHallOfHeroes", js_text)
        self.assertNotIn("patchedDossier", js_text)
        self.assertNotIn("patchedRecognition", js_text)
        self.assertNotIn("patchedCard", js_text)
        self.assertNotIn("patchedTooltip", js_text)
        self.assertNotIn("badge.removeAttribute('title');", js_text)
        self.assertNotIn("badge.style.pointerEvents = 'none';", js_text)
        self.assertNotIn("\u00c3\u0192", js_text)
        self.assertNotIn("\u00c3\u00d0", js_text)
        self.assertNotIn("\u00ef\u00bf\u00bd", js_text)
        self.assertIn("Latest dashboard scan:", js_text)
        self.assertIn("Raid-ready main.", js_text)
        self.assertIn("Level 70 but below raid-ready threshold.", js_text)
        self.assertIn("Missing item-level data; inspect profile source before roster decisions.", js_text)
        self.assertIn("Recently joined; review rank/spec when available.", js_text)
        self.assertIn("Recently rejoined; verify current rank and spec.", js_text)
        self.assertIn("Roster status is stable.", js_text)
        self.assertIn("Level 70", js_text)
        self.assertIn("Raid ready", js_text)
        self.assertIn("Staging for raid", js_text)
        self.assertIn("Needs gear", js_text)
        self.assertIn("Still advancing", js_text)
        self.assertNotIn("Equipped item level:", runtime_text)
        self.assertNotIn("Equipped item level:", js_text)
        self.assertNotIn("Battlefield Distinction", js_text)
        self.assertNotIn("Commendation Profile", js_text)
        self.assertNotIn("char-card-officer-badge", js_text)
        self.assertNotIn("Active PvP contributor.", js_text)
        self.assertNotIn("badge.setAttribute('data-tone', tone);", js_text)
        self.assertIn(".char-card-officer-layout", css_text)
        self.assertIn(".char-card-portrait {\n  width: min(100%, 160px);", css_text)
        self.assertIn("max-width: 120px;", css_text)
        self.assertIn(".char-card-header-badges {\n  width: 100%;", css_text)
        self.assertIn(".char-card-header-badges {\n  width: 100%;\n  justify-content: flex-start;", css_text)
        self.assertIn(".char-card-header-reigning-slot {\n  position: absolute;", css_text)
        self.assertIn(".char-card-header-reigning-badge {\n  max-width: 100%;\n  min-width: 0;", css_text)
        self.assertIn("cursor: default;", css_text)
        self.assertIn(".char-card-commendation-showcase", css_text)
        self.assertIn(".char-card-commendation-showcase-grid", css_text)
        self.assertIn(".char-card-commendation-showcase-body", css_text)
        self.assertIn(".char-card-commendation-showcase-summary-reigning-static {", css_text)
        self.assertIn(".char-card-commendation-showcase-item-reigning-static {", css_text)
        self.assertIn(".char-card-commendation-footprint-readiness {", css_text)
        self.assertIn(".tt-badge-weekly-readiness {", css_text)
        self.assertIn(".char-card-officer-footer", css_text)
        self.assertIn(".c-badge-weekly-readiness {", style_css_text)
        self.assertIn(".char-card {", css_text)
        self.assertIn("body[data-route-family=\"character\"]::before {", css_text)
        self.assertIn("body[data-route-family=\"character\"] .char-card {", css_text)
        self.assertIn(".char-card-gear-shell .empty-slot {", css_text)
        self.assertIn(".char-card-gear-shell .empty-slot .empty-slot-text {", css_text)
        self.assertIn(".char-card-gear-shell .empty-slot .gear-slot-quality {", css_text)
        self.assertNotIn(".char-card-summary-grid", css_text)
        self.assertNotIn(".char-card-spotlight", css_text)
        self.assertNotIn(".char-card-officer-badge", css_text)
        self.assertNotIn(".char-card {", style_css_text)
        self.assertNotIn("body[data-route-family=\"character\"]::before {", style_css_text)
        self.assertNotIn("body[data-route-family=\"character\"] .char-card {", style_css_text)
        self.assertNotIn(".char-card-gear-shell .empty-slot {", style_css_text)
        self.assertIn("buildDossierIntelligencePanel({", runtime_text)
        self.assertIn("buildDossierCommendationProfile({", runtime_text)
        self.assertIn("dashboardConfig: typeof config !== 'undefined' ? config : {}", runtime_text)
        self.assertIn("timelineEvents: typeof timelineData !== 'undefined' ? timelineData : []", runtime_text)
        self.assertIn(".char-card-commendation-showcase-summary {\n  width: 100%;", css_text)
        self.assertIn(".char-card-commendation-showcase-summary-icon {\n  width: 48px;", css_text)
        self.assertIn(".char-card-commendation-showcase-item[open] > .char-card-commendation-showcase-body {", css_text)
        self.assertIn(".char-card-commendation-showcase-history-line {\n  display: block;", css_text)
        self.assertIn(".char-card-header-reigning-badge {\n  max-width: 100%;\n  min-width: 0;\n  width: fit-content;", css_text)
        identity_decl = runtime_text.index("const identity = getDossierIdentitySnapshot(p, char);")
        activity_decl = runtime_text.index("const activity = getDossierActivitySnapshot(p, char);")
        self.assertLess(identity_decl, runtime_text.index("text: identity.levelLabel"))
        self.assertLess(identity_decl, runtime_text.index("text: identity.mainAltLabel"))
        self.assertLess(activity_decl, runtime_text.index("activity.label === 'Recently active'"))
        self.assertLess(runtime_text.index("const reigningBadges = typeof buildDossierReigning === 'function'"), runtime_text.index("reigningBadges.forEach"))

    def test_dossier_officer_brief_uses_canonical_equipped_item_level(self):
        js_text = Path("render/src/js/features/character_dossier/dossier_view.js").read_text(encoding="utf-8")
        roster_rows = json.loads(Path("asset/roster.json").read_text(encoding="utf-8"))

        self.assertTrue(any(
            isinstance(row.get("profile"), dict) and row["profile"].get("equipped_item_level", 0) > 0
            for row in roster_rows
            if isinstance(row, dict)
        ))
        self.assertTrue(any(
            isinstance(row.get("equipped"), dict) and row["equipped"].get("equipped_item_level", 0) > 0
            for row in roster_rows
            if isinstance(row, dict)
        ))

        self.assertIn("function getDossierEquippedItemLevel(profile, source = null)", js_text)
        self.assertIn("profile?.equipped_item_level", js_text)
        self.assertIn("source?.equipped_item_level", js_text)
        self.assertIn("profile?.equipped?.equipped_item_level", js_text)
        self.assertIn("source?.equipped?.equipped_item_level", js_text)
        self.assertIn("source?.profile?.equipped_item_level", js_text)
        self.assertIn("const ilvl = getDossierEquippedItemLevel(profile, source);", js_text)
        self.assertIn("const equippedIlvl = getDossierEquippedItemLevel(profile, source);", js_text)
        self.assertIn("if (identity.level >= 70 && equippedIlvl <= 0)", js_text)
        self.assertLess(
            js_text.index("const equippedIlvl = getDossierEquippedItemLevel(profile, source);"),
            js_text.index("if (identity.level >= 70 && equippedIlvl <= 0)"),
        )
        self.assertIn("Missing item-level data; inspect profile source before roster decisions.", js_text)
        self.assertNotIn("equippedIlvl = 0", js_text)


if __name__ == "__main__":
    unittest.main()
