from pathlib import Path
import unittest


class AnalyticsRenderTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.template_text = Path("render/dashboard_template.html").read_text(encoding="utf-8")
        cls.style_text = Path("render/style.css").read_text(encoding="utf-8")
        cls.analytics_css = Path("render/src/css/features/analytics/analytics.css").read_text(encoding="utf-8")
        cls.mobile_css = Path("render/src/css/features/mobile/mobile.css").read_text(encoding="utf-8")
        cls.analytics_cards_text = Path("render/src/js/features/home_analytics/analytics_cards.js").read_text(encoding="utf-8")
        cls.script_text = Path("render/script.js").read_text(encoding="utf-8")
        cls.html_dashboard_text = Path("render/html_dashboard.py").read_text(encoding="utf-8")

    def test_analytics_route_markup_and_scope_copy(self):
        template = self.template_text

        self.assertIn('id="analytics-view"', template)
        self.assertIn('class="analytics-hero-section"', template)
        self.assertIn('id="analytics-snapshot-section"', template)
        self.assertIn('class="analytics-snapshot-grid"', template)
        self.assertIn('id="analytics-campaign-history-section"', template)
        self.assertIn('id="analytics-campaign-history-card"', template)
        self.assertIn('Campaign History', template)
        self.assertIn('Archived Weeks', template)
        self.assertIn('Latest Week', template)
        self.assertIn('Campaign Entries', template)
        self.assertIn('Reigning Titles', template)
        self.assertIn('Open Campaign Archive', template)
        self.assertIn('href="#campaign-archive"', template)
        self.assertIn('No archived campaign weeks are available yet.', template)
        self.assertIn('id="analytics-readiness-funnel-section"', template)
        self.assertIn('id="analytics-readiness-funnel-card"', template)
        self.assertIn('id="analytics-readiness-funnel-stages"', template)
        self.assertIn('Roster Readiness Funnel', template)
        self.assertIn('Readiness funnel data is not available for this snapshot.', template)
        self.assertIn('id="analytics-roster-composition-section"', template)
        self.assertIn('id="analytics-roster-composition-card"', template)
        self.assertIn('id="analytics-roster-composition-summary"', template)
        self.assertIn('id="analytics-roster-composition-note"', template)
        self.assertIn('id="analytics-roster-composition-types"', template)
        self.assertIn('id="analytics-roster-composition-classes"', template)
        self.assertIn('id="analytics-roster-composition-levels"', template)
        self.assertIn('id="analytics-roster-composition-cta"', template)
        self.assertIn('id="analytics-composition-charts"', template)
        self.assertIn('Roster Composition', template)
        self.assertIn('What the current snapshot looks like', template)
        self.assertIn('Roster composition data is not available for this snapshot.', template)
        self.assertIn('Some composition fields are unavailable from the current snapshot.', template)
        self.assertIn('Open detailed composition charts', template)
        self.assertIn('analytics-kpi-wrapper', template)
        self.assertIn('class="analytics-pressure-grid"', template)
        self.assertIn('class="analytics-readiness-grid"', template)
        self.assertIn('class="analytics-spotlight-grid"', template)
        self.assertIn('class="analytics-quick-routes"', template)
        self.assertIn('id="analyticsActivityChart"', template)
        self.assertIn('id="roleDonutChart"', template)
        self.assertIn('id="levelDistChart"', template)
        self.assertIn('Scope: raw roster totals, mains-only readiness, roster-known levels, and processed detail-eligible intelligence.', template)
        self.assertIn('What changed since the previous scan?', template)
        self.assertIn('Guild Roster', template)
        self.assertIn('Active Mains', template)
        self.assertIn('Raid-Ready Mains', template)
        self.assertIn('Avg Level 70 iLvl', template)
        self.assertIn('Analytics', template)
        self.assertIn('Open Analytics', template)
        self.assertNotIn('Advanced Analytics', template)
        self.assertNotIn('https://github.com/parvagans/Azeroths-Most-Wanted', template)
        self.assertNotIn('Recent Campaign Activity', template)
        self.assertNotIn('Campaign Chronicle', template)

    def test_analytics_css_is_owning_its_route_styles(self):
        html_dashboard = self.html_dashboard_text
        analytics_css = self.analytics_css
        mobile_css = self.mobile_css
        style_css = self.style_text
        analytics_cards = self.analytics_cards_text
        script_text = self.script_text

        self.assertIn('os.path.join(base_dir, "src", "css", "features", "search", "autocomplete.css")', html_dashboard)
        self.assertIn('os.path.join(base_dir, "src", "css", "features", "war_effort", "war_effort.css")', html_dashboard)
        self.assertIn('os.path.join(base_dir, "src", "css", "features", "character", "dossier.css")', html_dashboard)
        self.assertIn('os.path.join(base_dir, "src", "css", "features", "analytics", "analytics.css")', html_dashboard)

        self.assertIn('.analytics-view-container', analytics_css)
        self.assertIn('.analytics-hero-section', analytics_css)
        self.assertIn('.analytics-hero-scope', analytics_css)
        self.assertIn('.analytics-snapshot-section', analytics_css)
        self.assertIn('.analytics-snapshot-grid', analytics_css)
        self.assertIn('.analytics-snapshot-card', analytics_css)
        self.assertIn('.analytics-snapshot-status', analytics_css)
        self.assertIn('.analytics-snapshot-scope', analytics_css)
        self.assertIn('.analytics-campaign-history-section', analytics_css)
        self.assertIn('.analytics-campaign-history-card', analytics_css)
        self.assertIn('.analytics-campaign-history-metrics', analytics_css)
        self.assertIn('.analytics-campaign-history-cta', analytics_css)
        self.assertIn('.analytics-readiness-funnel-section', analytics_css)
        self.assertIn('.analytics-readiness-funnel-card', analytics_css)
        self.assertIn('.analytics-readiness-funnel-stages', analytics_css)
        self.assertIn('.analytics-readiness-funnel-stage', analytics_css)
        self.assertIn('.analytics-readiness-funnel-meter', analytics_css)
        self.assertIn('.analytics-readiness-funnel-fill', analytics_css)
        self.assertIn('.analytics-intel-section-composition', analytics_css)
        self.assertIn('.analytics-roster-composition-card', analytics_css)
        self.assertIn('.analytics-roster-composition-grid', analytics_css)
        self.assertIn('.analytics-roster-composition-panel', analytics_css)
        self.assertIn('.analytics-roster-composition-row', analytics_css)
        self.assertIn('.analytics-roster-composition-meter', analytics_css)
        self.assertIn('.analytics-roster-composition-fill', analytics_css)
        self.assertIn('.analytics-roster-composition-footer', analytics_css)
        self.assertIn('.analytics-roster-composition-cta', analytics_css)
        self.assertIn('.analytics-pressure-card', analytics_css)
        self.assertIn('.analytics-route-card', analytics_css)
        self.assertIn('.command-shell-analytics-role', analytics_css)
        self.assertIn('body[data-route-family="analytics"]::before', analytics_css)
        self.assertIn('renderAnalyticsSnapshotStrip', analytics_cards)
        self.assertIn('renderAnalyticsCampaignHistoryCard', analytics_cards)
        self.assertIn('renderAnalyticsReadinessFunnel', analytics_cards)
        self.assertIn('renderAnalyticsRosterComposition', analytics_cards)
        self.assertIn('formatAnalyticsSnapshotShareText', analytics_cards)
        self.assertIn('getAnalyticsRosterClass', analytics_cards)
        self.assertIn('getAnalyticsRosterLevel', analytics_cards)
        self.assertIn('buildAnalyticsCompositionRow', analytics_cards)
        self.assertIn("const cardEl = document.getElementById('analytics-readiness-funnel-card');", analytics_cards)
        self.assertIn("label: 'Guild Roster'", analytics_cards)
        self.assertIn("label: 'Active Mains'", analytics_cards)
        self.assertIn("label: 'Level 70 Mains'", analytics_cards)
        self.assertIn("label: 'Raid-Ready Mains'", analytics_cards)
        self.assertIn("const cardEl = document.getElementById('analytics-roster-composition-card');", analytics_cards)
        self.assertIn("if (!summaryEl || !noteEl || !typesEl || !classesEl || !levelsEl || !ctaEl) return;", analytics_cards)
        self.assertIn("const hasMissingCompositionFields = knownClassCount < totalRoster || knownLevelCount < totalRoster;", analytics_cards)
        self.assertIn("Roster composition data is not available for this snapshot.", analytics_cards)
        self.assertIn("Some composition fields are unavailable from the current snapshot.", analytics_cards)
        self.assertIn("ctaEl.setAttribute('href', '#analytics-composition-charts');", analytics_cards)
        self.assertIn("const cardEl = document.getElementById('analytics-campaign-history-card');", analytics_cards)
        self.assertIn("if (!cardEl) return;", analytics_cards)
        self.assertIn("const weeks = Array.isArray(archive.weeks) ? archive.weeks : [];", analytics_cards)
        self.assertIn("const stagesEl = document.getElementById('analytics-readiness-funnel-stages');", analytics_cards)
        self.assertIn("if (!stagesEl || !summaryEl || !noteEl || !emptyEl) return;", analytics_cards)
        self.assertIn("Readiness funnel data is not available for this snapshot.", analytics_cards)
        self.assertIn("ctaEl.setAttribute('href', '#campaign-archive');", analytics_cards)
        self.assertIn('formatAnalyticsSnapshotDelta', analytics_cards)
        self.assertIn("const cardEl = document.getElementById(cardId);", analytics_cards)
        self.assertIn("const analyticsTrends = dashboardConfig.global_trends || {};", script_text)
        self.assertIn("const analyticsConfigSource = dashboardConfig && Object.keys(dashboardConfig).length > 0 ? dashboardConfig : config;", script_text)
        self.assertIn("const campaignArchiveData = analyticsConfigSource && analyticsConfigSource.campaign_archive", script_text)
        self.assertIn("const trackedMainCount = getNumericConfigValue(", script_text)
        self.assertIn("const hasAnalyticsSnapshotData = (", script_text)
        self.assertIn("const analyticsGuildRosterTotal = getNumericConfigValue(", script_text)
        self.assertIn("guildRosterValue: analyticsGuildRosterTotal", script_text)
        self.assertIn("renderAnalyticsSnapshotStrip({", script_text)
        self.assertIn("renderAnalyticsCampaignHistoryCard(campaignArchiveData);", script_text)
        self.assertIn("renderAnalyticsReadinessFunnel({", script_text)
        self.assertIn("level70Mains: mainLvl70Count", script_text)
        self.assertIn("raidReadyMains: mainRaidReadyCount", script_text)
        self.assertIn("renderAnalyticsRosterComposition({", script_text)
        self.assertIn("roster: Array.isArray(rawGuildRoster) && rawGuildRoster.length > 0 ? rawGuildRoster : rosterData", script_text)
        self.assertIn("analytics-snapshot-section", script_text)
        self.assertIn(".analytics-snapshot-section, .analytics-summary-section, .analytics-intel-section", script_text)
        self.assertNotIn("display_total_members", script_text)

        self.assertIn(".analytics-campaign-history-metrics {\n    grid-template-columns: 1fr;", mobile_css)
        self.assertIn(".analytics-campaign-history-footer {\n    align-items: flex-start;\n    flex-direction: column;", mobile_css)
        self.assertIn(".analytics-campaign-history-cta {\n    width: 100%;", mobile_css)
        self.assertIn(".analytics-readiness-funnel-stages {\n    grid-template-columns: 1fr;", mobile_css)
        self.assertIn(".analytics-readiness-funnel-card {\n    padding: 16px;", mobile_css)
        self.assertIn(".analytics-readiness-funnel-stage {\n    padding: 13px 14px;", mobile_css)
        self.assertIn(".analytics-roster-composition-grid {\n    grid-template-columns: 1fr;", mobile_css)
        self.assertIn(".analytics-roster-composition-card {\n    padding: 16px;", mobile_css)
        self.assertIn(".analytics-roster-composition-panel {\n    padding: 13px 14px;", mobile_css)
        self.assertIn(".analytics-roster-composition-row-head {\n    flex-direction: column;", mobile_css)
        self.assertIn(".analytics-roster-composition-cta {\n    width: 100%;", mobile_css)

        self.assertNotIn('.analytics-view-container', style_css)
        self.assertNotIn('.analytics-snapshot-section', style_css)
        self.assertNotIn('.analytics-snapshot-grid', style_css)
        self.assertNotIn('.analytics-snapshot-card', style_css)
        self.assertNotIn('.analytics-snapshot-status', style_css)
        self.assertNotIn('.analytics-snapshot-scope', style_css)
        self.assertNotIn('.analytics-campaign-history-section', style_css)
        self.assertNotIn('.analytics-campaign-history-card', style_css)
        self.assertNotIn('.analytics-campaign-history-metrics', style_css)
        self.assertNotIn('.analytics-campaign-history-cta', style_css)
        self.assertNotIn('.analytics-readiness-funnel-section', style_css)
        self.assertNotIn('.analytics-readiness-funnel-card', style_css)
        self.assertNotIn('.analytics-readiness-funnel-stages', style_css)
        self.assertNotIn('.analytics-readiness-funnel-meter', style_css)
        self.assertNotIn('.analytics-intel-section-composition', style_css)
        self.assertNotIn('.analytics-roster-composition-card', style_css)
        self.assertNotIn('.analytics-roster-composition-grid', style_css)
        self.assertNotIn('.analytics-roster-composition-panel', style_css)
        self.assertNotIn('.analytics-roster-composition-row', style_css)
        self.assertNotIn('.analytics-roster-composition-meter', style_css)
        self.assertNotIn('.analytics-roster-composition-fill', style_css)
        self.assertNotIn('.analytics-roster-composition-footer', style_css)
        self.assertNotIn('.analytics-roster-composition-cta', style_css)
        self.assertNotIn('.analytics-pressure-card', style_css)
        self.assertNotIn('.analytics-route-card', style_css)
        self.assertNotIn('.command-shell-analytics-role', style_css)
        self.assertNotIn('analytics-', style_css)


if __name__ == "__main__":
    unittest.main()
