from pathlib import Path
import unittest


class AnalyticsRenderTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.template_text = Path("render/dashboard_template.html").read_text(encoding="utf-8")
        cls.style_text = Path("render/style.css").read_text(encoding="utf-8")
        cls.analytics_css = Path("render/src/css/features/analytics/analytics.css").read_text(encoding="utf-8")
        cls.mobile_css = Path("render/src/css/features/mobile/mobile.css").read_text(encoding="utf-8")
        cls.analytics_cards_text = Path("render/src/js/features/home_analytics/analytics_cards.js").read_text(encoding="utf-8")
        cls.script_text = Path("render/script.js").read_text(encoding="utf-8")
        cls.html_dashboard_text = Path("render/html_dashboard.py").read_text(encoding="utf-8")

    def test_analytics_route_markup_and_scope_copy(self):
        template = self.template_text

        self.assertIn('id="analytics-view"', template)
        self.assertIn('class="analytics-hero-section"', template)
        self.assertIn('id="analytics-snapshot-section"', template)
        self.assertIn('class="analytics-snapshot-grid"', template)
        self.assertIn('id="analytics-campaign-history-section"', template)
        self.assertIn('id="analytics-campaign-history-card"', template)
        self.assertIn('Campaign History', template)
        self.assertIn('Archived Weeks', template)
        self.assertIn('Latest Week', template)
        self.assertIn('Campaign Entries', template)
        self.assertIn('Reigning Titles', template)
        self.assertIn('Open Campaign Archive', template)
        self.assertIn('href="#campaign-archive"', template)
        self.assertIn('No archived campaign weeks are available yet.', template)
        self.assertIn('id="analytics-readiness-funnel-section"', template)
        self.assertIn('id="analytics-readiness-funnel-card"', template)
        self.assertIn('id="analytics-readiness-funnel-stages"', template)
        self.assertIn('Roster Readiness Funnel', template)
        self.assertIn('Readiness funnel data is not available for this snapshot.', template)
        self.assertIn('id="analytics-readiness-gap-section"', template)
        self.assertIn('id="analytics-readiness-gap-card"', template)
        self.assertIn('id="analytics-readiness-gap-summary"', template)
        self.assertIn('id="analytics-readiness-gap-note"', template)
        self.assertIn('id="analytics-readiness-gap-meter-wrap"', template)
        self.assertIn('id="analytics-readiness-gap-stats"', template)
        self.assertIn('Readiness Gap', template)
        self.assertIn('How far is the level 70 main roster from raid-ready?', template)
        self.assertIn('Readiness gap data is not available for this snapshot.', template)
        self.assertIn('Some readiness gap fields are unavailable from the current snapshot.', template)
        self.assertIn('id="analytics-progression-readiness-section"', template)
        self.assertIn('id="analytics-level-distribution-card"', template)
        self.assertIn('id="analytics-level-distribution-list"', template)
        self.assertIn('id="analytics-ilvl-spread-card"', template)
        self.assertIn('id="analytics-ilvl-spread-list"', template)
        self.assertIn('Progression Readiness', template)
        self.assertIn('Level Distribution', template)
        self.assertIn('Max Level iLvl Spread', template)
        self.assertIn('These bars separate leveling progress from max-level gear readiness.', template)
        self.assertIn('id="analytics-honor-section"', template)
        self.assertIn('id="analytics-honor-card"', template)
        self.assertIn('id="analytics-honor-summary"', template)
        self.assertIn('id="analytics-honor-note"', template)
        self.assertIn('id="analytics-honor-stats"', template)
        self.assertIn('id="analytics-honor-leaderboard"', template)
        self.assertIn('Honor Snapshot', template)
        self.assertIn('Where PvP momentum is concentrated', template)
        self.assertIn('Top HK Characters', template)
        self.assertIn('Honor snapshot data is not available for this snapshot.', template)
        self.assertIn('Some HK fields are unavailable from the current snapshot.', template)
        self.assertIn('Open PvP Ladder', template)
        self.assertIn('href="#ladder-pvp"', template)
        self.assertNotIn('Guild Health Summary', template)
        self.assertNotIn('id="kpi-total-hks"', template)
        self.assertNotIn('id="kpi-box-pve"', template)
        self.assertNotIn('id="kpi-box-ready"', template)
        self.assertNotIn('id="kpi-box-pvp"', template)
        self.assertIn('id="analytics-roster-composition-section"', template)
        self.assertIn('id="analytics-roster-composition-card"', template)
        self.assertIn('id="analytics-roster-composition-summary"', template)
        self.assertIn('id="analytics-roster-composition-note"', template)
        self.assertIn('id="analytics-roster-composition-types"', template)
        self.assertIn('id="analytics-roster-composition-classes"', template)
        self.assertIn('id="analytics-roster-composition-levels"', template)
        self.assertIn('id="analytics-composition-charts"', template)
        self.assertIn('id="analytics-distribution-note"', template)
        self.assertIn('id="analytics-class-distribution-card"', template)
        self.assertIn('id="analytics-class-distribution-list"', template)
        self.assertIn('id="analytics-race-distribution-card"', template)
        self.assertIn('id="analytics-race-distribution-list"', template)
        self.assertIn('Roster Composition', template)
        self.assertIn('What the current snapshot looks like', template)
        self.assertIn('Roster composition data is not available for this snapshot.', template)
        self.assertIn('Some composition fields are unavailable from the current snapshot.', template)
        self.assertIn('Roster Distribution', template)
        self.assertIn('How the scanned roster breaks down', template)
        self.assertIn('Class is the primary comparison. Race is a lighter secondary snapshot. Click any bar to inspect that slice.', template)
        self.assertIn('Scanned roster', template)
        self.assertIn('Class Distribution', template)
        self.assertIn('Represented Classes', template)
        self.assertIn('Race Distribution', template)
        self.assertIn('Secondary Flavor View', template)
        self.assertIn('Some roster distribution fields are unavailable from the current snapshot.', template)
        self.assertNotIn('href="#analytics-composition-charts"', template)
        self.assertNotIn('analyticsClassChart', template)
        self.assertNotIn('raceDistChart', template)
        self.assertIn('class="analytics-pressure-grid"', template)
        self.assertIn('class="analytics-readiness-grid"', template)
        self.assertIn('class="analytics-spotlight-grid"', template)
        self.assertIn('class="analytics-quick-routes"', template)
        self.assertIn('id="analyticsActivityChart"', template)
        self.assertIn('id="roleDonutChart"', template)
        self.assertNotIn('id="levelDistChart"', template)
        self.assertNotIn('id="ilvlDistChart"', template)
        self.assertIn('Scope: raw roster totals, mains-only readiness, roster-known levels, and processed detail-eligible intelligence.', template)
        self.assertIn('What changed since the previous scan?', template)
        self.assertIn('Guild Roster', template)
        self.assertIn('Active Mains', template)
        self.assertIn('Raid-Ready Mains', template)
        self.assertIn('Avg Level 70 iLvl', template)
        self.assertNotIn('Guild Health Summary', template)
        self.assertNotIn('id="kpi-total-hks"', template)
        self.assertNotIn('id="kpi-box-pve"', template)
        self.assertNotIn('id="kpi-box-ready"', template)
        self.assertNotIn('id="kpi-box-pvp"', template)
        self.assertIn('Analytics', template)
        self.assertIn('Open Analytics', template)
        self.assertNotIn('Advanced Analytics', template)
        self.assertNotIn('https://github.com/parvagans/Azeroths-Most-Wanted', template)
        self.assertNotIn('Recent Campaign Activity', template)
        self.assertNotIn('Campaign Chronicle', template)

    def test_analytics_css_is_owning_its_route_styles(self):
        html_dashboard = self.html_dashboard_text
        analytics_css = self.analytics_css
        mobile_css = self.mobile_css
        style_css = self.style_text
        analytics_cards = self.analytics_cards_text
        script_text = self.script_text

        self.assertIn('os.path.join(base_dir, "src", "css", "features", "search", "autocomplete.css")', html_dashboard)
        self.assertIn('os.path.join(base_dir, "src", "css", "features", "war_effort", "war_effort.css")', html_dashboard)
        self.assertIn('os.path.join(base_dir, "src", "css", "features", "character", "dossier.css")', html_dashboard)
        self.assertIn('os.path.join(base_dir, "src", "css", "features", "analytics", "analytics.css")', html_dashboard)

        self.assertIn('.analytics-view-container', analytics_css)
        self.assertIn('.analytics-hero-section', analytics_css)
        self.assertIn('.analytics-hero-scope', analytics_css)
        self.assertIn('.analytics-snapshot-section', analytics_css)
        self.assertIn('.analytics-snapshot-grid', analytics_css)
        self.assertIn('.analytics-snapshot-card', analytics_css)
        self.assertIn('.analytics-snapshot-status', analytics_css)
        self.assertIn('.analytics-snapshot-scope', analytics_css)
        self.assertIn('.analytics-campaign-history-section', analytics_css)
        self.assertIn('.analytics-campaign-history-card', analytics_css)
        self.assertIn('.analytics-campaign-history-metrics', analytics_css)
        self.assertIn('.analytics-campaign-history-cta', analytics_css)
        self.assertIn('.analytics-honor-section', analytics_css)
        self.assertIn('.analytics-honor-card', analytics_css)
        self.assertIn('.analytics-honor-summary', analytics_css)
        self.assertIn('.analytics-honor-note', analytics_css)
        self.assertIn('.analytics-honor-stats', analytics_css)
        self.assertIn('.analytics-honor-stat', analytics_css)
        self.assertIn('.analytics-honor-leaderboard-shell', analytics_css)
        self.assertIn('.analytics-honor-leaderboard-head', analytics_css)
        self.assertIn('.analytics-honor-leaderboard', analytics_css)
        self.assertIn('.analytics-honor-row', analytics_css)
        self.assertIn('.analytics-honor-row-fill', analytics_css)
        self.assertIn('.analytics-honor-cta', analytics_css)
        self.assertIn('.analytics-readiness-funnel-section', analytics_css)
        self.assertIn('.analytics-readiness-funnel-card', analytics_css)
        self.assertIn('.analytics-readiness-funnel-stages', analytics_css)
        self.assertIn('.analytics-readiness-funnel-stage', analytics_css)
        self.assertIn('.analytics-readiness-funnel-meter', analytics_css)
        self.assertIn('.analytics-readiness-funnel-fill', analytics_css)
        self.assertIn('.analytics-readiness-gap-section', analytics_css)
        self.assertIn('.analytics-readiness-gap-card', analytics_css)
        self.assertIn('.analytics-readiness-gap-stats', analytics_css)
        self.assertIn('.analytics-readiness-gap-stat', analytics_css)
        self.assertIn('.analytics-readiness-gap-meter-wrap', analytics_css)
        self.assertIn('.analytics-readiness-gap-meter', analytics_css)
        self.assertIn('.analytics-readiness-gap-fill', analytics_css)
        self.assertIn('.analytics-readiness-gap-label', analytics_css)
        self.assertIn('.analytics-readiness-gap-value', analytics_css)
        self.assertIn('.analytics-readiness-gap-meter-meta', analytics_css)
        self.assertIn('.analytics-readiness-gap-summary', analytics_css)
        self.assertIn('.analytics-readiness-gap-note', analytics_css)
        self.assertIn('.analytics-progression-readiness-section', analytics_css)
        self.assertIn('.analytics-progression-grid', analytics_css)
        self.assertIn('.analytics-progression-card', analytics_css)
        self.assertIn('.analytics-progression-list', analytics_css)
        self.assertIn('.analytics-progression-item', analytics_css)
        self.assertIn('.analytics-progression-item-head', analytics_css)
        self.assertIn('.analytics-progression-item-value', analytics_css)
        self.assertIn('.analytics-progression-meter', analytics_css)
        self.assertIn('.analytics-progression-fill', analytics_css)
        self.assertIn('.analytics-progression-empty-state', analytics_css)
        self.assertIn('.analytics-intel-section-composition', analytics_css)
        self.assertIn('.analytics-distribution-section', analytics_css)
        self.assertIn('.analytics-distribution-grid', analytics_css)
        self.assertIn('.analytics-distribution-card', analytics_css)
        self.assertIn('.analytics-distribution-card-secondary', analytics_css)
        self.assertIn('.analytics-distribution-note', analytics_css)
        self.assertIn('.analytics-distribution-scope', analytics_css)
        self.assertIn('.analytics-distribution-head', analytics_css)
        self.assertIn('.analytics-distribution-item', analytics_css)
        self.assertIn('.analytics-distribution-item-head', analytics_css)
        self.assertIn('.analytics-distribution-item-value', analytics_css)
        self.assertIn('.analytics-distribution-meter', analytics_css)
        self.assertIn('.analytics-distribution-fill', analytics_css)
        self.assertIn('.analytics-distribution-item-meta', analytics_css)
        self.assertIn('.analytics-distribution-empty-state', analytics_css)
        self.assertIn('.analytics-roster-composition-card', analytics_css)
        self.assertIn('.analytics-roster-composition-grid', analytics_css)
        self.assertIn('.analytics-roster-composition-panel', analytics_css)
        self.assertIn('.analytics-roster-composition-row', analytics_css)
        self.assertIn('.analytics-roster-composition-meter', analytics_css)
        self.assertIn('.analytics-roster-composition-fill', analytics_css)
        self.assertIn('.analytics-roster-composition-footer-note', analytics_css)
        self.assertNotIn('.analytics-card-composition .chart-canvas-wrapper', analytics_css)
        self.assertNotIn('.analytics-card-readiness .chart-canvas-wrapper', analytics_css)
        self.assertIn('.analytics-pressure-card', analytics_css)
        self.assertIn('.analytics-route-card', analytics_css)
        self.assertIn('.command-shell-analytics-role', analytics_css)
        self.assertIn('body[data-route-family="analytics"]::before', analytics_css)
        self.assertIn('renderAnalyticsSnapshotStrip', analytics_cards)
        self.assertIn('renderAnalyticsCampaignHistoryCard', analytics_cards)
        self.assertIn('renderAnalyticsReadinessFunnel', analytics_cards)
        self.assertIn('renderAnalyticsReadinessGap', analytics_cards)
        self.assertIn('renderAnalyticsHonorSnapshot', analytics_cards)
        self.assertIn('renderAnalyticsRosterComposition', analytics_cards)
        self.assertIn('renderAnalyticsProgressionReadiness', analytics_cards)
        self.assertIn('formatAnalyticsSnapshotShareText', analytics_cards)
        self.assertIn('formatAnalyticsProgressionShareText', analytics_cards)
        self.assertIn('getAnalyticsRosterClass', analytics_cards)
        self.assertIn('getAnalyticsRosterLevel', analytics_cards)
        self.assertIn('getAnalyticsRosterIlvl', analytics_cards)
        self.assertIn('buildAnalyticsCompositionRow', analytics_cards)
        self.assertIn('buildAnalyticsProgressionRow', analytics_cards)
        self.assertIn('buildAnalyticsReadinessGapStat', analytics_cards)
        self.assertIn('buildAnalyticsHonorSnapshotStat', analytics_cards)
        self.assertIn('buildAnalyticsHonorSnapshotRow', analytics_cards)
        self.assertIn('getAnalyticsRosterHonorKills', analytics_cards)
        self.assertIn("const cardEl = document.getElementById('analytics-readiness-funnel-card');", analytics_cards)
        self.assertIn("label: 'Guild Roster'", analytics_cards)
        self.assertIn("label: 'Active Mains'", analytics_cards)
        self.assertIn("label: 'Level 70 Mains'", analytics_cards)
        self.assertIn("label: 'Raid-Ready Mains'", analytics_cards)
        self.assertIn("const cardEl = document.getElementById('analytics-readiness-gap-card');", analytics_cards)
        self.assertIn("if (!summaryEl || !noteEl || !statsEl || !meterWrapEl || !meterFillEl || !meterMetaEl) return;", analytics_cards)
        self.assertIn("Readiness gap data is not available for this snapshot.", analytics_cards)
        self.assertIn("Some readiness gap fields are unavailable from the current snapshot.", analytics_cards)
        self.assertIn("const sectionEl = document.getElementById('analytics-progression-readiness-section');", analytics_cards)
        self.assertIn("if (!noteEl || !levelCardEl || !levelListEl || !ilvlCardEl || !ilvlListEl) return;", analytics_cards)
        self.assertIn("Level distribution data is not available for this snapshot.", analytics_cards)
        self.assertIn("Item-level spread data is not available for this snapshot.", analytics_cards)
        self.assertIn("Some progression readiness fields are unavailable from the current snapshot.", analytics_cards)
        self.assertIn("const cardEl = document.getElementById('analytics-honor-card');", analytics_cards)
        self.assertIn("if (!summaryEl || !noteEl || !statsEl || !leaderboardEl || !ctaEl) return;", analytics_cards)
        self.assertIn("Honor snapshot data is not available for this snapshot.", analytics_cards)
        self.assertIn("Some HK fields are unavailable from the current snapshot.", analytics_cards)
        self.assertIn("ctaEl.setAttribute('href', '#ladder-pvp');", analytics_cards)
        self.assertIn("const hkEntries = roster", analytics_cards)
        self.assertIn("buildAnalyticsHonorSnapshotRow({", analytics_cards)
        self.assertIn("HK-active characters", analytics_cards)
        self.assertIn("Avg HKs / active character", analytics_cards)
        self.assertIn("Current snapshot", analytics_cards)
        self.assertIn("label: 'Raid-ready mains'", analytics_cards)
        self.assertIn("label: 'Level 70 mains'", analytics_cards)
        self.assertIn("label: 'Not-yet raid-ready'", analytics_cards)
        self.assertIn("label: 'Raid-ready share'", analytics_cards)
        self.assertIn("label: 'Avg level 70 iLvl'", analytics_cards)
        self.assertIn('renderAnalyticsRosterDistribution', analytics_cards)
        self.assertIn('getAnalyticsRosterRace', analytics_cards)
        self.assertIn('buildAnalyticsDistributionItem', analytics_cards)
        self.assertNotIn('#analytics-composition-charts', analytics_cards)
        self.assertIn("const cardEl = document.getElementById('analytics-roster-composition-card');", analytics_cards)
        self.assertIn("if (!summaryEl || !noteEl || !typesEl || !classesEl || !levelsEl) return;", analytics_cards)
        self.assertIn("const hasMissingCompositionFields = knownClassCount < totalRoster || knownLevelCount < totalRoster;", analytics_cards)
        self.assertIn("Roster composition data is not available for this snapshot.", analytics_cards)
        self.assertIn("Some composition fields are unavailable from the current snapshot.", analytics_cards)
        self.assertIn("const cardEl = document.getElementById('analytics-composition-charts');", analytics_cards)
        self.assertIn("if (!noteEl || !classListEl || !raceListEl) return;", analytics_cards)
        self.assertIn("Roster distribution data is not available for this snapshot.", analytics_cards)
        self.assertIn("Some roster distribution fields are unavailable from the current snapshot.", analytics_cards)
        self.assertIn("class-${label.toLowerCase()}", analytics_cards)
        self.assertIn("filter-race-${label.toLowerCase()}", analytics_cards)
        self.assertIn("analytics-distribution-item", analytics_cards)
        self.assertNotIn("levelDistChart", analytics_cards)
        self.assertNotIn("ilvlDistChart", analytics_cards)
        self.assertIn("const cardEl = document.getElementById('analytics-campaign-history-card');", analytics_cards)
        self.assertIn("if (!cardEl) return;", analytics_cards)
        self.assertIn("const weeks = Array.isArray(archive.weeks) ? archive.weeks : [];", analytics_cards)
        self.assertIn("const stagesEl = document.getElementById('analytics-readiness-funnel-stages');", analytics_cards)
        self.assertIn("if (!stagesEl || !summaryEl || !noteEl || !emptyEl) return;", analytics_cards)
        self.assertIn("Readiness funnel data is not available for this snapshot.", analytics_cards)
        self.assertIn("ctaEl.setAttribute('href', '#campaign-archive');", analytics_cards)
        self.assertIn('formatAnalyticsSnapshotDelta', analytics_cards)
        self.assertIn("const cardEl = document.getElementById(cardId);", analytics_cards)
        self.assertIn("const analyticsTrends = dashboardConfig.global_trends || {};", script_text)
        self.assertIn("const analyticsConfigSource = dashboardConfig && Object.keys(dashboardConfig).length > 0 ? dashboardConfig : config;", script_text)
        self.assertIn("const campaignArchiveData = analyticsConfigSource && analyticsConfigSource.campaign_archive", script_text)
        self.assertIn("const trackedMainCount = getNumericConfigValue(", script_text)
        self.assertIn("const hasAnalyticsSnapshotData = (", script_text)
        self.assertIn("const analyticsGuildRosterTotal = getNumericConfigValue(", script_text)
        self.assertIn("guildRosterValue: analyticsGuildRosterTotal", script_text)
        self.assertIn("renderAnalyticsSnapshotStrip({", script_text)
        self.assertIn("renderAnalyticsCampaignHistoryCard(campaignArchiveData);", script_text)
        self.assertIn("renderAnalyticsReadinessFunnel({", script_text)
        self.assertIn("renderAnalyticsReadinessGap({", script_text)
        self.assertIn("level70Mains: mainLvl70Count", script_text)
        self.assertIn("raidReadyMains: mainRaidReadyCount", script_text)
        self.assertIn("avgIlvl70: mainAvgIlvl", script_text)
        self.assertIn("const analyticsRosterSnapshot = Array.isArray(rawGuildRoster) && rawGuildRoster.length > 0 ? rawGuildRoster : rosterData;", script_text)
        self.assertIn("renderAnalyticsRosterComposition({", script_text)
        self.assertIn("roster: analyticsRosterSnapshot", script_text)
        self.assertIn("renderAnalyticsRosterDistribution({", script_text)
        self.assertIn("analytics-snapshot-section", script_text)
        self.assertIn(".analytics-snapshot-section, .analytics-honor-section, .analytics-intel-section", script_text)
        self.assertNotIn("display_total_members", script_text)

        self.assertIn(".analytics-campaign-history-metrics {\n    grid-template-columns: 1fr;", mobile_css)
        self.assertIn(".analytics-campaign-history-footer {\n    align-items: flex-start;\n    flex-direction: column;", mobile_css)
        self.assertIn(".analytics-campaign-history-cta {\n    width: 100%;", mobile_css)
        self.assertIn(".analytics-honor-section", mobile_css)
        self.assertIn(".analytics-honor-card {\n    padding: 16px;", mobile_css)
        self.assertIn(".analytics-honor-summary,\n  .analytics-honor-note,\n  .analytics-honor-row-meta {\n    font-size: 13px;", mobile_css)
        self.assertIn(".analytics-honor-stats {\n    grid-template-columns: 1fr;", mobile_css)
        self.assertIn(".analytics-honor-row {\n    padding: 13px 14px 14px;", mobile_css)
        self.assertIn(".analytics-honor-row-head {\n    grid-template-columns: auto minmax(0, 1fr);", mobile_css)
        self.assertIn(".analytics-honor-leaderboard-head {\n    align-items: flex-start;\n    flex-direction: column;", mobile_css)
        self.assertIn(".analytics-readiness-funnel-stages {\n    grid-template-columns: 1fr;", mobile_css)
        self.assertIn(".analytics-readiness-funnel-card {\n    padding: 16px;", mobile_css)
        self.assertIn(".analytics-readiness-funnel-stage {\n    padding: 13px 14px;", mobile_css)
        self.assertIn(".analytics-readiness-gap-section", mobile_css)
        self.assertIn(".analytics-readiness-gap-card {\n    padding: 16px;", mobile_css)
        self.assertIn(".analytics-readiness-gap-stats {\n    grid-template-columns: 1fr;", mobile_css)
        self.assertIn(".analytics-readiness-gap-stat {\n    padding: 13px 14px;", mobile_css)
        self.assertIn(".analytics-readiness-gap-summary,\n  .analytics-readiness-gap-note,\n  .analytics-readiness-gap-meter-meta {\n    font-size: 13px;", mobile_css)
        self.assertIn("Progression readiness bars and cards", mobile_css)
        self.assertIn(".analytics-progression-grid {\n    grid-template-columns: 1fr;", mobile_css)
        self.assertIn(".analytics-progression-card {\n    padding: 16px;", mobile_css)
        self.assertIn(".analytics-progression-head {\n    align-items: flex-start;\n    flex-direction: column;", mobile_css)
        self.assertIn(".analytics-progression-item-head {\n    align-items: flex-start;\n    flex-direction: column;", mobile_css)
        self.assertIn(".analytics-progression-item-value {\n    white-space: normal;", mobile_css)
        self.assertIn(".analytics-progression-item {\n    padding: 12px 13px 13px;", mobile_css)
        self.assertIn(".analytics-roster-composition-grid {\n    grid-template-columns: 1fr;", mobile_css)
        self.assertIn(".analytics-roster-composition-card {\n    padding: 16px;", mobile_css)
        self.assertIn(".analytics-roster-composition-panel {\n    padding: 13px 14px;", mobile_css)
        self.assertIn(".analytics-roster-composition-row-head {\n    flex-direction: column;", mobile_css)
        self.assertIn(".analytics-roster-composition-footer-note {\n    text-align: left;", mobile_css)
        self.assertIn(".analytics-distribution-grid {\n    grid-template-columns: 1fr;", mobile_css)
        self.assertIn(".analytics-distribution-card {\n    padding: 16px;", mobile_css)
        self.assertIn(".analytics-distribution-head {\n    align-items: flex-start;\n    flex-direction: column;", mobile_css)
        self.assertIn(".analytics-distribution-item-head {\n    align-items: flex-start;\n    flex-direction: column;", mobile_css)
        self.assertIn(".analytics-distribution-item-value {\n    white-space: normal;", mobile_css)
        self.assertIn(".analytics-distribution-note {\n    font-size: 13px;", mobile_css)
        self.assertIn(".analytics-distribution-item-meta {\n    font-size: 12px;", mobile_css)
        self.assertIn(".analytics-distribution-item {\n    padding: 12px 13px 13px;", mobile_css)

        self.assertNotIn('.analytics-view-container', style_css)
        self.assertNotIn('.analytics-snapshot-section', style_css)
        self.assertNotIn('.analytics-snapshot-grid', style_css)
        self.assertNotIn('.analytics-snapshot-card', style_css)
        self.assertNotIn('.analytics-snapshot-status', style_css)
        self.assertNotIn('.analytics-snapshot-scope', style_css)
        self.assertNotIn('.analytics-campaign-history-section', style_css)
        self.assertNotIn('.analytics-campaign-history-card', style_css)
        self.assertNotIn('.analytics-campaign-history-metrics', style_css)
        self.assertNotIn('.analytics-campaign-history-cta', style_css)
        self.assertNotIn('.analytics-honor-section', style_css)
        self.assertNotIn('.analytics-honor-card', style_css)
        self.assertNotIn('.analytics-honor-summary', style_css)
        self.assertNotIn('.analytics-honor-note', style_css)
        self.assertNotIn('.analytics-honor-stats', style_css)
        self.assertNotIn('.analytics-honor-stat', style_css)
        self.assertNotIn('.analytics-honor-leaderboard-shell', style_css)
        self.assertNotIn('.analytics-honor-leaderboard-head', style_css)
        self.assertNotIn('.analytics-honor-leaderboard', style_css)
        self.assertNotIn('.analytics-honor-row', style_css)
        self.assertNotIn('.analytics-honor-row-fill', style_css)
        self.assertNotIn('.analytics-honor-cta', style_css)
        self.assertNotIn('.analytics-readiness-funnel-section', style_css)
        self.assertNotIn('.analytics-readiness-funnel-card', style_css)
        self.assertNotIn('.analytics-readiness-funnel-stages', style_css)
        self.assertNotIn('.analytics-readiness-funnel-meter', style_css)
        self.assertNotIn('.analytics-readiness-gap-section', style_css)
        self.assertNotIn('.analytics-readiness-gap-card', style_css)
        self.assertNotIn('.analytics-readiness-gap-stats', style_css)
        self.assertNotIn('.analytics-readiness-gap-stat', style_css)
        self.assertNotIn('.analytics-readiness-gap-meter-wrap', style_css)
        self.assertNotIn('.analytics-readiness-gap-meter', style_css)
        self.assertNotIn('.analytics-readiness-gap-fill', style_css)
        self.assertNotIn('.analytics-readiness-gap-label', style_css)
        self.assertNotIn('.analytics-readiness-gap-value', style_css)
        self.assertNotIn('.analytics-readiness-gap-meter-meta', style_css)
        self.assertNotIn('.analytics-readiness-gap-summary', style_css)
        self.assertNotIn('.analytics-readiness-gap-note', style_css)
        self.assertNotIn('.analytics-progression-readiness-section', style_css)
        self.assertNotIn('.analytics-progression-grid', style_css)
        self.assertNotIn('.analytics-progression-card', style_css)
        self.assertNotIn('.analytics-progression-list', style_css)
        self.assertNotIn('.analytics-progression-item', style_css)
        self.assertNotIn('.analytics-progression-meter', style_css)
        self.assertNotIn('.analytics-progression-fill', style_css)
        self.assertNotIn('.analytics-card-composition .chart-canvas-wrapper', style_css)
        self.assertNotIn('.analytics-card-readiness .chart-canvas-wrapper', style_css)
        self.assertNotIn('.analytics-intel-section-composition', style_css)
        self.assertNotIn('.analytics-distribution-section', style_css)
        self.assertNotIn('.analytics-distribution-grid', style_css)
        self.assertNotIn('.analytics-distribution-card', style_css)
        self.assertNotIn('.analytics-distribution-item', style_css)
        self.assertNotIn('.analytics-roster-composition-card', style_css)
        self.assertNotIn('.analytics-roster-composition-grid', style_css)
        self.assertNotIn('.analytics-roster-composition-panel', style_css)
        self.assertNotIn('.analytics-roster-composition-row', style_css)
        self.assertNotIn('.analytics-roster-composition-meter', style_css)
        self.assertNotIn('.analytics-roster-composition-fill', style_css)
        self.assertNotIn('.analytics-roster-composition-footer-note', style_css)
        self.assertNotIn('.analytics-pressure-card', style_css)
        self.assertNotIn('.analytics-route-card', style_css)
        self.assertNotIn('.command-shell-analytics-role', style_css)
        self.assertNotIn('analytics-', style_css)


if __name__ == "__main__":
    unittest.main()
