import unittest
from pathlib import Path


class CharacterIntelligenceRenderTests(unittest.TestCase):
    def test_dossier_template_includes_character_intelligence_hook(self):
        template_text = Path("render/dashboard_template.html").read_text(encoding="utf-8")

        self.assertIn('class="info-box char-card-intelligence-shell"', template_text)
        self.assertIn('class="char-card-intelligence-profile"', template_text)

    def test_dossier_js_includes_prestige_identity_and_reigning_header(self):
        html_dashboard_text = Path("render/html_dashboard.py").read_text(encoding="utf-8")
        js_text = Path("render/src/js/features/character_dossier/dossier_view.js").read_text(encoding="utf-8")
        runtime_text = Path("render/script.js").read_text(encoding="utf-8")
        style_css_text = Path("render/style.css").read_text(encoding="utf-8")
        css_text = Path("render/src/css/features/character/dossier.css").read_text(encoding="utf-8")

        self.assertIn('os.path.join(base_dir, "src", "css", "features", "character", "dossier.css")', html_dashboard_text)
        self.assertIn("function buildDossierIntelligencePanel", js_text)
        self.assertIn("function buildDossierOfficerBriefPanel", js_text)
        self.assertIn("function buildDossierIntelligenceSection", js_text)
        self.assertIn("function getDossierIdentitySnapshot", js_text)
        self.assertIn("function getDossierMovementSnapshot", js_text)
        self.assertIn("function buildDossierOfficerNotes", js_text)
        self.assertIn("function buildDossierRecognitionItems", js_text)
        self.assertIn("function formatDossierRecognitionDate", js_text)
        self.assertIn("function getDossierRecognitionHistoryLines", js_text)
        self.assertIn("function getDossierReigningWeekLabel", js_text)
        self.assertIn("function formatDossierBadgeHistoryEntry", js_text)
        self.assertIn("function buildDossierBadgeHistory", js_text)
        self.assertIn("function buildDossierReigning", js_text)
        self.assertIn("function buildDossierPrestigeShowcase", js_text)
        self.assertIn("Officer Brief", js_text)
        self.assertIn("Recognition Record", js_text)
        self.assertIn("Awards & Footprint", js_text)
        self.assertIn("Prestige Showcase", js_text)
        self.assertIn("Reigning iLvl Champion", js_text)
        self.assertIn("Reigning HK Champion", js_text)
        self.assertIn("Biggest Upgrades / iLvl", js_text)
        self.assertIn("Deadliest / HKs", js_text)
        self.assertIn("const prevMvps = dashboardConfig && typeof dashboardConfig === 'object'", js_text)
        self.assertIn("const hasCurrentPrevMvp = Boolean((prevMvps.pve && prevMvps.pve.name) || (prevMvps.pvp && prevMvps.pvp.name));", js_text)
        self.assertIn("tt-badge-weekly-loot", js_text)
        self.assertIn("tt-badge-weekly-xp", js_text)
        self.assertIn("tt-badge-weekly-hks", js_text)
        self.assertIn("tt-badge-weekly-zenith", js_text)
        self.assertIn("tt-badge-vanguard", js_text)
        self.assertIn("tt-badge-gold", js_text)
        self.assertIn("tt-badge-silver", js_text)
        self.assertIn("tt-badge-bronze", js_text)
        self.assertIn("tt-badge-pve c-badge-reigning c-badge-reigning-pve", js_text)
        self.assertIn("tt-badge-pvp c-badge-reigning c-badge-reigning-pvp", js_text)
        self.assertIn("const DOSSIER_PRESTIGE_ICONS = Object.freeze({", js_text)
        self.assertIn("dragonHoard: '\\u{1F409}'", js_text)
        self.assertIn("heroJourney: '\\u{1F6E1}\\uFE0F'", js_text)
        self.assertIn("bloodEnemy: '\\u{1FA78}'", js_text)
        self.assertIn("zenith: '\\u26A1\\uFE0F'", js_text)
        self.assertIn("vanguard: '\\u{1F396}\\uFE0F'", js_text)
        self.assertIn("crown: '\\u{1F451}'", js_text)
        self.assertIn("sword: '\\u2694\\uFE0F'", js_text)
        self.assertIn("gold: '\\u{1F947}'", js_text)
        self.assertIn("silver: '\\u{1F948}'", js_text)
        self.assertIn("bronze: '\\u{1F949}'", js_text)
        self.assertIn("const reigningIconByCategory = {", js_text)
        self.assertIn("badgeText: label,", js_text)
        self.assertIn("pve: DOSSIER_PRESTIGE_ICONS.crown,", js_text)
        self.assertIn("pvp: DOSSIER_PRESTIGE_ICONS.sword", js_text)
        self.assertIn("const DASHBOARD_BADGE_ICONS = Object.freeze({", runtime_text)
        self.assertIn("crown: '\\u{1F451}'", runtime_text)
        self.assertIn("sword: '\\u2694\\uFE0F'", runtime_text)
        self.assertIn("gold: '\\u{1F947}'", runtime_text)
        self.assertIn("silver: '\\u{1F948}'", runtime_text)
        self.assertIn("bronze: '\\u{1F949}'", runtime_text)
        self.assertIn("vanguard: '\\u{1F396}\\uFE0F'", runtime_text)
        self.assertIn("shield: '\\u{1F6E1}\\uFE0F'", runtime_text)
        self.assertIn("blood: '\\u{1FA78}'", runtime_text)
        self.assertIn("dragon: '\\u{1F409}'", runtime_text)
        self.assertIn("lightning: '\\u26A1\\uFE0F'", runtime_text)
        self.assertIn("const vanguardRequested = cleanBadgeTypes.includes('vanguard');", js_text)
        self.assertIn("const warEffortEntries = Array.isArray(week?.war_effort) ? week.war_effort : [];", js_text)
        self.assertIn("detail: `${dateLabel} ${DOSSIER_PRESTIGE_SEPARATOR} ${categoryLabel} ${DOSSIER_PRESTIGE_SEPARATOR} ${medalLabel} ${DOSSIER_PRESTIGE_SEPARATOR} Rank #${rank} ${DOSSIER_PRESTIGE_SEPARATOR} Score ${score.toLocaleString()}`", js_text)
        self.assertIn("detail: `${dateLabel} ${DOSSIER_PRESTIGE_SEPARATOR} ${sourceLabel} / ${categoryLabel} ${DOSSIER_PRESTIGE_SEPARATOR} ${roleLabel}`", js_text)
        self.assertIn("detail: `${dateLabel} ${DOSSIER_PRESTIGE_SEPARATOR} ${sourceLabel} / ${categoryLabel} ${DOSSIER_PRESTIGE_SEPARATOR} Vanguard`", js_text)
        self.assertIn("detail: `${dateLabel} ${DOSSIER_PRESTIGE_SEPARATOR} ${displayName}`", js_text)
        self.assertIn("summaryCount.textContent = `x${item.count}`;", js_text)
        self.assertIn("summaryIcon.textContent = item.icon;", js_text)
        self.assertIn("const headerReigningSlotEl = clone.querySelector('.char-card-header-reigning-slot') || headerBadgesEl;", runtime_text)
        self.assertIn("appendFullCardReigningBadge(headerReigningSlotEl, reigningInfo, index === 0);", runtime_text)
        self.assertIn("const reigningBadges = typeof buildDossierReigning === 'function'", runtime_text)
        self.assertIn("buildDossierReigning({", runtime_text)
        self.assertIn("profile: p,", runtime_text)
        self.assertIn("source: char,", runtime_text)
        self.assertNotIn("addBadge(isPveReigning ? 1 : 0, 'Current Reigning PvE Champion!', 'tt-badge-pve', '👑', '👑 Reign');", runtime_text)
        self.assertNotIn("addBadge(isPvpReigning ? 1 : 0, 'Current Reigning PvP Champion!', 'tt-badge-pvp', '⚔️', '⚔️ Reign');", runtime_text)
        self.assertIn("Dragon's Hoard", js_text)
        self.assertIn("Blood of the Enemy", js_text)
        self.assertIn("Latest archive week:", js_text)
        self.assertNotIn("PvE Ladder Medals", js_text)
        self.assertNotIn("PvP Ladder Medals", js_text)
        self.assertNotIn("icon: 'DH'", js_text)
        self.assertNotIn("icon: 'HJ'", js_text)
        self.assertNotIn("icon: 'BoE'", js_text)
        self.assertNotIn("icon: 'ZN'", js_text)
        self.assertNotIn("icon: 'VG'", js_text)
        self.assertNotIn("Ãƒ", js_text)
        self.assertNotIn("Ã", js_text)
        self.assertNotIn("ï¿½", js_text)
        self.assertIn("Latest dashboard scan:", js_text)
        self.assertIn("Raid-ready main.", js_text)
        self.assertIn("Level 70 but below raid-ready threshold.", js_text)
        self.assertIn("Missing item-level data; inspect profile source before roster decisions.", js_text)
        self.assertIn("Recently joined; review rank/spec when available.", js_text)
        self.assertIn("Recently rejoined; verify current rank and spec.", js_text)
        self.assertIn("Roster status is stable.", js_text)
        self.assertIn("Level 70", js_text)
        self.assertIn("Raid ready", js_text)
        self.assertIn("Staging for raid", js_text)
        self.assertIn("Needs gear", js_text)
        self.assertIn("Still advancing", js_text)
        self.assertNotIn("Battlefield Distinction", js_text)
        self.assertNotIn("Commendation Profile", js_text)
        self.assertNotIn("char-card-officer-badge", js_text)
        self.assertNotIn("Active PvP contributor.", js_text)
        self.assertNotIn("badge.setAttribute('data-tone', tone);", js_text)
        self.assertIn(".char-card-officer-layout", css_text)
        self.assertIn(".char-card-portrait {\n  width: min(100%, 160px);", css_text)
        self.assertIn("max-width: 120px;", css_text)
        self.assertIn(".char-card-header-badges {\n  width: 100%;", css_text)
        self.assertIn(".char-card-header-badges {\n  width: 100%;\n  justify-content: flex-start;", css_text)
        self.assertIn(".char-card-header-reigning-slot {\n  position: absolute;", css_text)
        self.assertIn(".char-card-header-reigning-badge {\n  max-width: 100%;\n  min-width: 0;", css_text)
        self.assertIn(".char-card-commendation-showcase", css_text)
        self.assertIn(".char-card-commendation-showcase-grid", css_text)
        self.assertIn(".char-card-commendation-showcase-body", css_text)
        self.assertIn(".char-card-officer-footer", css_text)
        self.assertIn(".char-card {", css_text)
        self.assertIn("body[data-route-family=\"character\"]::before {", css_text)
        self.assertIn("body[data-route-family=\"character\"] .char-card {", css_text)
        self.assertIn(".char-card-gear-shell .empty-slot {", css_text)
        self.assertIn(".char-card-gear-shell .empty-slot .empty-slot-text {", css_text)
        self.assertIn(".char-card-gear-shell .empty-slot .gear-slot-quality {", css_text)
        self.assertNotIn(".char-card-summary-grid", css_text)
        self.assertNotIn(".char-card-spotlight", css_text)
        self.assertNotIn(".char-card-officer-badge", css_text)
        self.assertNotIn(".char-card {", style_css_text)
        self.assertNotIn("body[data-route-family=\"character\"]::before {", style_css_text)
        self.assertNotIn("body[data-route-family=\"character\"] .char-card {", style_css_text)
        self.assertNotIn(".char-card-gear-shell .empty-slot {", style_css_text)
        self.assertIn("buildDossierIntelligencePanel({", runtime_text)
        self.assertIn("buildDossierCommendationProfile({", runtime_text)
        self.assertIn("dashboardConfig: typeof config !== 'undefined' ? config : {}", runtime_text)
        self.assertIn("timelineEvents: typeof timelineData !== 'undefined' ? timelineData : []", runtime_text)
        self.assertIn(".char-card-commendation-showcase-summary {\n  width: 100%;", css_text)
        self.assertIn(".char-card-commendation-showcase-summary-icon {\n  width: 48px;", css_text)
        self.assertIn(".char-card-commendation-showcase-item[open] > .char-card-commendation-showcase-body {", css_text)
        self.assertIn(".char-card-commendation-showcase-history-line {\n  display: block;", css_text)
        identity_decl = runtime_text.index("const identity = getDossierIdentitySnapshot(p, char);")
        activity_decl = runtime_text.index("const activity = getDossierActivitySnapshot(p, char);")
        self.assertLess(identity_decl, runtime_text.index("text: identity.levelLabel"))
        self.assertLess(identity_decl, runtime_text.index("text: identity.mainAltLabel"))
        self.assertLess(activity_decl, runtime_text.index("activity.label === 'Recently active'"))
        self.assertLess(runtime_text.index("const reigningBadges = typeof buildDossierReigning === 'function'"), runtime_text.index("reigningBadges.forEach"))


if __name__ == "__main__":
    unittest.main()
